include profile.properties

.PHONY: html fix-html data toc ncx opf gen


default: gen


clean:
	@rm -fr .tmp/*

build: clean data res ncx opf
	@echo 'Create ebook file by kindlegen ...'
	kindlegen -dont_append_source -c2 -verbose .tmp/vim-help.opf -o vim-help.azw3
	@echo '  Generate kf8 file, ok'
	@echo 'Build success'

html:
	@echo 'Convert text to html ...'
	@find $(DOC_PATH) -name '*.txt' | xargs $(DOC_PATH)/vim2html.pl $(DOC_PATH)/tags > /dev/null
	@$(DOC_PATH)/vim2html.pl $(DOC_PATH)/tags $(DOC_PATH)/tags
	@mv *html .tmp
	@mv vim-stylesheet.css .tmp
	@echo "  Generate `ls .tmp | wc -l |tr -d ' '` html files"

fix-html: html
	@echo 'Preparing clean html ...'
	@sed -i '' '/<p><i>Generated by vim2html/d' .tmp/*.html
	@echo '  Remove vim2html information'
	@sed -i '' 's/vim:tw=78:.*:ft=help[a-z=:]*//g' .tmp/*.html
	@echo '  Clean useless content'

data: fix-html
	@echo 'Search toc data to xml ...'
	@egrep '^(<code class="se|\|)' .tmp/help.html >toc.txt
	@sed -i '' 's/"tags#help-tags/"tags.html/g' toc.txt
	@sed -i '' 's/^<code class="section">\(.*\)<\/code>/<\/chapter><chapter title="\1">/g' toc.txt
	@sed -i '' 's/^|<a href="\(.*\)">\(.*\)<\/a>|\(.*\)/<section title="\2" href="\1" src="\1">\3<\/section>/g' toc.txt
	@sed -i '' 's/\( src=".*\)#.*"/\1"/g' toc.txt
	@sed -E -i '' 's/[[:space:]]+/ /g' toc.txt
	@sed -i '' 's/> />/g' toc.txt
	@sed -i '' 's/title="\(.*\) ">/title="\1">/g' toc.txt
	@sed -i '' '1 s/^<\/chapter>/<root>/' toc.txt
	@sed -E -i '' '1,10 {/"\(iccf|bugs|tutor|copying|www\)"/d;}' toc.txt
	@sed -E -i '' '1,6 {/iccf|www/d;}' toc.txt
	@echo '</chapter></root>' >> toc.txt
	@mv toc.txt toc.xml
	@echo '  Generate toc data file'

toc:
	@echo 'Create toc.html ...'
	@xsltproc vim-help.toc.html-template.xsl toc.xml > .tmp/toc.html

opf:
	@echo 'Create vim-help.opf ...'
	@xsltproc vim-help.opf-template.xsl toc.xml > .tmp/vim-help.opf

ncx:
	@echo 'Create vim-help.ncx ...'
	@xsltproc vim-help.toc.ncx-template.xsl toc.xml > .tmp/vim-help.ncx

res:
	@cp -r static/* .tmp

gen: data res ncx opf
	@echo 'Create ebook file by kindlegen ...'
	kindlegen -dont_append_source -verbose .tmp/vim-help.opf -o vim-help.azw3
	@echo '  Generate kf8 file, ok'
